<?php

namespace AppBundle\Repository;

/**
 * APIKeyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APIKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
