<?php

namespace AppBundle\Repository;

/**
 * JokePostRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JokePostRepository extends \Doctrine\ORM\EntityRepository
{
}
