AppBundle\Entity\Vote:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\VoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        up:
            type: boolean
        down:
            type: boolean
    manyToOne:
        jokepost:
            targetEntity: JokePost
            inversedBy: votes
            joinColumn:
                name: jokepost_id
                referencedColumnName: id
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
